apiVersion: v1
kind: Service
metadata:
  name: yarp-service
spec:
  type: NodePort
  selector:
    app: yarp-webapp
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 80
      nodePort: 30101
